services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    hostname: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    hostname: schema-registry
    ports:
      - "8085:8081"
    depends_on:
      - broker
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:29092
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8086:8080"
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_SCHEMA_REGISTRY: http://schema-registry:8081
      KAFKA_CLUSTERS_0_JMX_PORT: 9999
      KAFKA_CLUSTERS_0_JMX_HOST: broker
      KAFKA_CLUSTERS_0_JMX_ENABLED: "true"
      KAFKA_CLUSTERS_0_JMX_USER: ""
      KAFKA_CLUSTERS_0_JMX_PASS: ""
      KAFKA_CLUSTERS_0_JMX_TYPE: "JMX"
      KAFKA_CLUSTERS_0_JMX_POLLING_INTERVAL: 10000
      KAFKA_CLUSTERS_0_JMX_REFRESH_METADATA: "true"
      KAFKA_CLUSTERS_0_JMX_CACHE_TTL: 60000
      KAFKA_CLUSTERS_0_JMX_TIMEOUT: 10000
      KAFKA_CLUSTERS_0_JMX_KAFKA_VERSION: "2.8.0"
      KAFKA_CLUSTERS_0_JMX_KAFKA_PACKAGE_VERSION: "2.8.0"
      KAFKA_CLUSTERS_0_JMX_KAFKA_JMX_VERSION: "2.0.0"
      KAFKA_CLUSTERS_0_JMX_KAFKA_JMX_PACKAGE_VERSION: "2.0.0"
      KAFKA_CLUSTERS_0_JMX_KAFKA_JMX_AGENT_VERSION: "1.76"
      KAFKA_CLUSTERS_0_JMX_KAFKA_JMX_AGENT_PACKAGE_VERSION: "1.76"
      KAFKA_CLUSTERS_0_JMX_KAFKA_JMX_AGENT_AGENT_ID: "kafka"
      KAFKA_CLUSTERS_0_JMX_KAFKA_JMX_AGENT_AGENT_TYPE: "kafka"
      KAFKA_CLUSTERS_0_JMX_KAFKA_JMX_AGENT_AGENT_DESCRIPTION: "Kafka JMX Agent"
      KAFKA_CLUSTERS_0_JMX_KAFKA_JMX_AGENT_AGENT_CLASS: "org.apache.kafka.metrics.KafkaJmxReporter"
      DYNAMIC_CONFIG_ENABLED: 'true'

